// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: model/odd.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_HAD Type = 0
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "HAD",
	}
	Type_value = map[string]int32{
		"HAD": 0,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_model_odd_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_model_odd_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_model_odd_proto_rawDescGZIP(), []int{0}
}

type Outcome int32

const (
	Outcome_HOME Outcome = 0
	Outcome_AWAY Outcome = 1
	Outcome_DRAW Outcome = 2
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "HOME",
		1: "AWAY",
		2: "DRAW",
	}
	Outcome_value = map[string]int32{
		"HOME": 0,
		"AWAY": 1,
		"DRAW": 2,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_model_odd_proto_enumTypes[1].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_model_odd_proto_enumTypes[1]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_model_odd_proto_rawDescGZIP(), []int{1}
}

type Odd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MatchId string  `protobuf:"bytes,2,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Outcome Outcome `protobuf:"varint,3,opt,name=outcome,proto3,enum=model.Outcome" json:"outcome,omitempty"`
	Type    Type    `protobuf:"varint,4,opt,name=type,proto3,enum=model.Type" json:"type,omitempty"`
	Odd     float32 `protobuf:"fixed32,5,opt,name=odd,proto3" json:"odd,omitempty"`
}

func (x *Odd) Reset() {
	*x = Odd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_odd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Odd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Odd) ProtoMessage() {}

func (x *Odd) ProtoReflect() protoreflect.Message {
	mi := &file_model_odd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Odd.ProtoReflect.Descriptor instead.
func (*Odd) Descriptor() ([]byte, []int) {
	return file_model_odd_proto_rawDescGZIP(), []int{0}
}

func (x *Odd) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Odd) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *Odd) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_HOME
}

func (x *Odd) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_HAD
}

func (x *Odd) GetOdd() float32 {
	if x != nil {
		return x.Odd
	}
	return 0
}

type Bet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Odd  *Odd    `protobuf:"bytes,2,opt,name=odd,proto3" json:"odd,omitempty"`
	Size float32 `protobuf:"fixed32,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *Bet) Reset() {
	*x = Bet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_odd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_model_odd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_model_odd_proto_rawDescGZIP(), []int{1}
}

func (x *Bet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bet) GetOdd() *Odd {
	if x != nil {
		return x.Odd
	}
	return nil
}

func (x *Bet) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_model_odd_proto protoreflect.FileDescriptor

var file_model_odd_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x6f, 0x64, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x8d, 0x01, 0x0a, 0x03, 0x4f, 0x64, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x6f,
	0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x52, 0x07, 0x6f, 0x75,
	0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x64, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x6f, 0x64, 0x64, 0x22, 0x47, 0x0a, 0x03, 0x42, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1c, 0x0a, 0x03, 0x6f, 0x64, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4f, 0x64, 0x64, 0x52, 0x03, 0x6f, 0x64, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x2a, 0x0f, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x48, 0x41, 0x44,
	0x10, 0x00, 0x2a, 0x27, 0x0a, 0x07, 0x4f, 0x75, 0x74, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x48, 0x4f, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x41, 0x57, 0x41, 0x59, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x52, 0x41, 0x57, 0x10, 0x02, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x77, 0x69, 0x73, 0x74, 0x65,
	0x64, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x73, 0x70, 0x65, 0x72, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_model_odd_proto_rawDescOnce sync.Once
	file_model_odd_proto_rawDescData = file_model_odd_proto_rawDesc
)

func file_model_odd_proto_rawDescGZIP() []byte {
	file_model_odd_proto_rawDescOnce.Do(func() {
		file_model_odd_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_odd_proto_rawDescData)
	})
	return file_model_odd_proto_rawDescData
}

var file_model_odd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_model_odd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_model_odd_proto_goTypes = []interface{}{
	(Type)(0),    // 0: model.Type
	(Outcome)(0), // 1: model.Outcome
	(*Odd)(nil),  // 2: model.Odd
	(*Bet)(nil),  // 3: model.Bet
}
var file_model_odd_proto_depIdxs = []int32{
	1, // 0: model.Odd.outcome:type_name -> model.Outcome
	0, // 1: model.Odd.type:type_name -> model.Type
	2, // 2: model.Bet.odd:type_name -> model.Odd
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_model_odd_proto_init() }
func file_model_odd_proto_init() {
	if File_model_odd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_odd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Odd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_odd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_odd_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_odd_proto_goTypes,
		DependencyIndexes: file_model_odd_proto_depIdxs,
		EnumInfos:         file_model_odd_proto_enumTypes,
		MessageInfos:      file_model_odd_proto_msgTypes,
	}.Build()
	File_model_odd_proto = out.File
	file_model_odd_proto_rawDesc = nil
	file_model_odd_proto_goTypes = nil
	file_model_odd_proto_depIdxs = nil
}
